---

- name: Manage sysvinit services
  become: true
  when:
    - ansible_service_mgr == "sysvinit"
  loop: "{{ services_state_list + services_state_list_group + services_state_list_host | flatten(levels=1) }}"
  loop_control:
    loop_var: service
    label: "{{ service.sysvinit.name }}, state: {{ service.state }}"
  ignore_errors: true
  ansible.builtin.service:
    name: "{{ service.sysvinit.name }}"
    enabled: "{{ service.enabled }}"
    state: "{{ service.state }}"
    runlevel: "{{ service.sysvinit.runlevel | default(omit) }}"


- name: Manage systemd services
  become: true
  when:
    - ansible_service_mgr == "systemd"
  loop: "{{ services_state_list + services_state_list_group + services_state_list_host | flatten(levels=1) }}"
  loop_control:
    loop_var: service
    label: "service: {{ service.systemd.name }}, state: {{ service.state }}"
  ignore_errors: true
  ansible.builtin.systemd:
    name: "{{ service.systemd.name }}"
    enabled: "{{ service.enabled }}"
    state: "{{ service.state }}"
    masked: "{{ service.systemd.masked | default(omit) }}"
    scope: "{{ service.systemd.scope | default(omit) }}"
    daemon_reload: true
